### ISSUE TITLE
Syntax highlighting broken in "case" with negative numbers

### ISSUE THREAD

**Issue by adrian-goe** [gleam-lang/tree-sitter-gleam#108]
This is an example code I currently use for my aoc day 2
```gleam
let num = -1
case num {
    -1 -> -1
    -2 -> -1
    -3 -> -1
    1 -> 1
    2 -> 1
    3 -> 1
    _ -> 0
}
```
Everything after this is no longer highlighted.

![image](https://github.com/user-attachments/assets/6e8b6846-9a74-45c7-885a-08ec45f4205b)

I asked in the gleam discord, and Isaac Harris-Holt was able to reproduce it in zed and nvim. 

gleam 1.6.2
Zed 0.163.2

**Comment by isaacharrisholt** [comment]
Yep, can confirm I managed to replicate this. TS version: 00f128d

**Comment by adrian-goe** [comment]
also githubs file view is also broken

![image](https://github.com/user-attachments/assets/652aa20a-86f7-4d23-a4de-4a8f965de1d5)
https://github.com/adrian-goe/adventofcode2024/blob/16dc4eabe53cb7a3b0464ba61cb0efa3e7e1ee61/src/aoc_2024/day_2.gleam

also in diff:
![image](https://github.com/user-attachments/assets/f2ef1d5a-cbb8-4b1b-8692-7802ae56de53)

https://github.com/adrian-goe/adventofcode2024/commit/16dc4eabe53cb7a3b0464ba61cb0efa3e7e1ee61

**Comment by lpil** [comment]
Just tested with the current version of the tree sitter and it does not have this problem with the supplied code. Please update to the latest version (066704e4826699e754d351e3bbe12bf2e51de9d8)
