### ISSUE TITLE
Function name sometimes not highlighted

### ISSUE THREAD

**Issue by lpil** [gleam-lang/tree-sitter-gleam#25]
Hello! I found an instance in which a function name does not get highlighted. It's not clear to me why this is right away

![image](https://user-images.githubusercontent.com/6134406/168885923-5f14bbdb-20e2-425a-91c6-7790d4584f47.png)

https://github.com/gleam-lang/stdlib/blob/f9d57db847ff2a8471c9136bd309c870b610d04d/src/gleam/uri.gleam#L325

**Comment by the-mikedavis** [comment]
It looks like the scopes for locals may not be correct for function parameters: if `string` is captured as a `@variable.parameter` earlier in the document it will throw off the highlights later:

<img src="https://user-images.githubusercontent.com/21230295/168890911-3edd0997-e4e9-4ddd-a062-7fbd3297d69a.png" width=550/>

Should be a small fix I think.
