### ISSUE TITLE
Update for Gleam v0.24's <> operator

### ISSUE THREAD

**Issue by lpil** [gleam-lang/tree-sitter-gleam#38]
Hello!

The latest Gleam release has added a new syntax, the `<>` operator.

Could we update this library to support it please? 🙏 

https://github.com/gleam-lang/gleam/blob/6202f1b7b2aa15767b5a45410e870060befb4fa3/compiler-core/src/parse.rs#L847

https://github.com/gleam-lang/gleam/blob/6202f1b7b2aa15767b5a45410e870060befb4fa3/compiler-core/src/parse.rs#L2735

Thanks!

**Comment by the-mikedavis** [comment]
I can take a look at this 🙂

It looks like `<>` is supported in patterns in `case`s - is it supported in guards expressions too?

**Comment by lpil** [comment]
Thank you!

Not yet, no.

**Comment by J3RN** [comment]
Just merged @the-mikedavis' PR for this feature; will do a proper v0.24 release tomorrow morning
