### ISSUE TITLE
Support `panic` and `let assert`

### ISSUE THREAD

**Issue by lpil** [gleam-lang/tree-sitter-gleam#45]
Hello!

The upcoming Gleam release as 2 syntax changes. `panic` (which can go anywhere an expression goes, like todo but without the string argument), and `let assert <pattern> = <expression>`, which is the new syntax for `assert <pattern> = <expression>`.

Thanks!

**Comment by inoas** [comment]
should assert simply be replaced by `let assert` or should both work?

**Comment by lpil** [comment]
Both are currently valid Gleam syntax.

**Comment by inoas** [comment]
https://github.com/gleam-lang/tree-sitter-gleam/pull/46
https://github.com/gleam-lang/tree-sitter-gleam/pull/48

**Comment by J3RN** [comment]
Closed by #46 and #50
