### ISSUE TITLE
Parser changes

### ISSUE THREAD

**Issue by lpil** [gleam-lang/tree-sitter-gleam#51]
Hello there!

Gleam's parser has been changed to only permit `let` and `use` directly within functions and block. Code such as this will now be rejected:

```gleam
let x = let y = 1
```

This is a subset of the previously accepted syntax so the current tree sitter will still parse all valid programs, but perhaps perhaps it wants to be restricted also?

**Comment by the-mikedavis** [comment]
I think tree-sitter parsers shouldn't be so restrictive that they are basically linters but on the other hand it's a nice experience when your syntax highlighting hints that your program will not compile. So I think we should stay close to the upstream parser here and restrict this syntax 👍

**Comment by J3RN** [comment]
Agreed
