### ISSUE TITLE
Parsing error with new `@external` syntax

### ISSUE THREAD

**Issue by rawhat** [gleam-lang/tree-sitter-gleam#67]
The new updates seem to be working really well!  One spot where I'm seeing a parsing error is with `@external`.

![image](https://github.com/gleam-lang/tree-sitter-gleam/assets/2095509/0fa36495-6e35-483b-972d-2d6da622f5b6)

It seems like the `fn ...` block is failing to parse, I'm guessing due to missing curly braces.  If I add those, it parses successfully, but I obviously then get a syntax error from `gleam`.

It seems like the function isn't nested below the `attribute` so I'm not sure how easy this would be to change.

Thank you!

**Comment by the-mikedavis** [comment]
Ah I see, function bodies can be optional with the attribute syntax. I think this should only take a small change to fix, I'll post a PR
