### ISSUE TITLE
Easier/cleaner way to write tree-sitter grammar

### ISSUE THREAD

**Issue by mingodad** [gleam-lang/tree-sitter-gleam#97]
Here https://mingodad.github.io/lua-wasm-playground/ there is an easier/cleaner way to write tree-sitter grammars like `Gleam` (select `Tree-sitter-ebnf-generator-Gleam` from `Examples` then click `Run` to see a full commented out `grammar.js` from the `EBNF` variant describng the grammar in `
Input Text (arg[1])`).

I hope it can be helpful !

**Comment by lpil** [comment]
Thank you but I don't think we are looking to rewrite this project presently as it's working for us OK.

**Comment by mingodad** [comment]
Thank you for reply !
The beauty of it is that there is nothing to rewrite, it's done automatically:
- First time: quickjs https://github.com/mingodad/plgh/blob/main/json2ebnf-lua.js src/grammar.json > grammar.ebnf
- Now develop with grammar.ebnf as needed
- lua https://github.com/mingodad/lua-wasm-playground/blob/main/examples/tree-sitter-ebnf-generator-cmd.lua grammar.ebnf  > grammar.js
- tree-siter build
