### ISSUE TITLE
[bug] tree-sitter incorrectly labels comment inside function body as (function_body)

### ISSUE THREAD

**Issue by Juhan280** [gleam-lang/tree-sitter-gleam#98]
![Screenshot_20240907-115103_Termux](https://github.com/user-attachments/assets/47f0e7bd-c689-4dbe-8af1-232ba9b32f2b)

The code used in the example:
```gleam
fn name() -> Nil { 
	// comment

	Nil

	// comment

	Nil

	// comment
}
```

**Comment by the-mikedavis** [comment]
This may be a bug in neovim instead of here. Using `:tree-sitter-subtree` on this example with Helix:

![gleam](https://github.com/user-attachments/assets/a1fd2be9-df05-45bd-94c7-def4ed8ac615)

**Comment by Juhan280** [comment]
Yeah, it might be. If i do `(comment) @c`, it still captures that comment despite it being labeled as `(function_body)`
